steps:
- task: DotNetCoreCLI@2
  displayName: Restore nugets
  inputs:
    command: restore
    arguments: --locked-mode --nologo
    restoreDirectory: $(Pipeline.Workspace)/.nuget/packages
    verbosityRestore: Minimal
