parameters:
- name: projectPath
  type: string
  default: '**/src/**/*.csproj'
- name: configuration
  type: string
  default: $(BuildConfiguration)
- name: publishArgs
  type: string
  default: ''
- name: publishWeb
  type: boolean
  default: false
- name: outputPath
  type: string
  default: $(build.artifactStagingDirectory)/publish

steps:
- task: DotNetCoreCLI@2
  displayName: Publish projects
  inputs:
    command: publish
    projects: ${{ parameters.projectPath }}
    configuration: ${{ parameters.configuration }}
    publishWebProjects: ${{ parameters.publishWeb }}
    arguments: --no-restore --no-build --nologo -o ${{ parameters.outputPath }} ${{ parameters.publishArgs }}
