parameters:
- name: downloadPath
  type: string
  default: $(System.ArtifactsDirectory)
- name: artifactName
  type: string

steps:
- task: DownloadBuildArtifacts@0
  displayName: Downloads ${{ parameters.artifactName }} artifact
  inputs:
    downloadType: single
    artifactName: ${{ parameters.artifactName }}
    downloadPath: ${{ parameters.downloadPath }}
