parameters:
- name: jdkVersion
  type: string
  default: 13
- name: jdkArch
  type: string
  values:
    - x64
    - x86
  default: x64

steps:
- task: JavaToolInstaller@0
  displayName: Install JDK ${{ parameters.jdkVersion }}
  inputs:
    versionSpec: ${{ parameters.jdkVersion }}
    jdkArchitectureOption: ${{ parameters.jdkArch }}
    jdkSourceOption: PreInstalled
