parameters:
- name: packagesToPush
  type: string
  default: $(Pipeline.Workspace)/pack/*.nupkg
- name: feedName
  type: string
  default: NugetKritikos

steps:
- task: NuGetCommand@2
  displayName: Push NuGet Package
  inputs:
    command: push
    packagesToPush: ${{ parameters.packagesToPush }}
    nuGetFeedType: external
    publishFeedCredentials: ${{ parameters.feedName }}
