// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace Esentis.Ieemdb.Persistence.Migrations
{
    public partial class updatesmoviecountriesrelation : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_MovieCountries_Movies_MovieId1",
                table: "MovieCountries");

            migrationBuilder.DropIndex(
                name: "IX_MovieCountries_MovieId1",
                table: "MovieCountries");

            migrationBuilder.DropColumn(
                name: "MovieId1",
                table: "MovieCountries");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<long>(
                name: "MovieId1",
                table: "MovieCountries",
                type: "bigint",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_MovieCountries_MovieId1",
                table: "MovieCountries",
                column: "MovieId1");

            migrationBuilder.AddForeignKey(
                name: "FK_MovieCountries_Movies_MovieId1",
                table: "MovieCountries",
                column: "MovieId1",
                principalTable: "Movies",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
