// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace Esentis.Ieemdb.Persistence.Migrations
{
    public partial class addmoviecountriesrelation : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_MovieCountry_Countries_CountryId",
                table: "MovieCountry");

            migrationBuilder.DropForeignKey(
                name: "FK_MovieCountry_Movies_MovieId",
                table: "MovieCountry");

            migrationBuilder.DropPrimaryKey(
                name: "PK_MovieCountry",
                table: "MovieCountry");

            migrationBuilder.RenameTable(
                name: "MovieCountry",
                newName: "MovieCountries");

            migrationBuilder.RenameIndex(
                name: "IX_MovieCountry_CountryId",
                table: "MovieCountries",
                newName: "IX_MovieCountries_CountryId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_MovieCountries",
                table: "MovieCountries",
                columns: new[] { "MovieId", "CountryId" });

            migrationBuilder.AddForeignKey(
                name: "FK_MovieCountries_Countries_CountryId",
                table: "MovieCountries",
                column: "CountryId",
                principalTable: "Countries",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_MovieCountries_Movies_MovieId",
                table: "MovieCountries",
                column: "MovieId",
                principalTable: "Movies",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_MovieCountries_Countries_CountryId",
                table: "MovieCountries");

            migrationBuilder.DropForeignKey(
                name: "FK_MovieCountries_Movies_MovieId",
                table: "MovieCountries");

            migrationBuilder.DropPrimaryKey(
                name: "PK_MovieCountries",
                table: "MovieCountries");

            migrationBuilder.RenameTable(
                name: "MovieCountries",
                newName: "MovieCountry");

            migrationBuilder.RenameIndex(
                name: "IX_MovieCountries_CountryId",
                table: "MovieCountry",
                newName: "IX_MovieCountry_CountryId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_MovieCountry",
                table: "MovieCountry",
                columns: new[] { "MovieId", "CountryId" });

            migrationBuilder.AddForeignKey(
                name: "FK_MovieCountry_Countries_CountryId",
                table: "MovieCountry",
                column: "CountryId",
                principalTable: "Countries",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_MovieCountry_Movies_MovieId",
                table: "MovieCountry",
                column: "MovieId",
                principalTable: "Movies",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
