// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace Esentis.Ieemdb.Persistence.Migrations
{
    public partial class Editsnamesonpeople : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "FirstName",
                table: "Writers");

            migrationBuilder.DropColumn(
                name: "LastName",
                table: "Writers");

            migrationBuilder.DropColumn(
                name: "FirstName",
                table: "Directors");

            migrationBuilder.DropColumn(
                name: "LastName",
                table: "Directors");

            migrationBuilder.DropColumn(
                name: "FirstName",
                table: "Actors");

            migrationBuilder.DropColumn(
                name: "LastName",
                table: "Actors");

            migrationBuilder.RenameColumn(
                name: "NormalizedLastName",
                table: "Writers",
                newName: "NormalizedFullName");

            migrationBuilder.RenameColumn(
                name: "NormalizedFirstName",
                table: "Writers",
                newName: "FullName");

            migrationBuilder.RenameColumn(
                name: "NormalizedLastName",
                table: "Directors",
                newName: "NormalizedFullName");

            migrationBuilder.RenameColumn(
                name: "NormalizedFirstName",
                table: "Directors",
                newName: "FullName");

            migrationBuilder.RenameColumn(
                name: "NormalizedLastName",
                table: "Actors",
                newName: "NormalizedFullName");

            migrationBuilder.RenameColumn(
                name: "NormalizedFirstName",
                table: "Actors",
                newName: "FullName");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "NormalizedFullName",
                table: "Writers",
                newName: "NormalizedLastName");

            migrationBuilder.RenameColumn(
                name: "FullName",
                table: "Writers",
                newName: "NormalizedFirstName");

            migrationBuilder.RenameColumn(
                name: "NormalizedFullName",
                table: "Directors",
                newName: "NormalizedLastName");

            migrationBuilder.RenameColumn(
                name: "FullName",
                table: "Directors",
                newName: "NormalizedFirstName");

            migrationBuilder.RenameColumn(
                name: "NormalizedFullName",
                table: "Actors",
                newName: "NormalizedLastName");

            migrationBuilder.RenameColumn(
                name: "FullName",
                table: "Actors",
                newName: "NormalizedFirstName");

            migrationBuilder.AddColumn<string>(
                name: "FirstName",
                table: "Writers",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "LastName",
                table: "Writers",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "FirstName",
                table: "Directors",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "LastName",
                table: "Directors",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "FirstName",
                table: "Actors",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "LastName",
                table: "Actors",
                type: "text",
                nullable: false,
                defaultValue: "");
        }
    }
}
