// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace Esentis.Ieemdb.Persistence.Migrations
{
  public partial class Preparesdatabaseforfulltextsearch : Migration
  {
    protected override void Up(MigrationBuilder migrationBuilder)
    {
      migrationBuilder.RenameColumn(
          name: "NormalizedName",
          table: "Writers",
          newName: "NormalizedSearch");

      migrationBuilder.RenameColumn(
          name: "NormalizedTitle",
          table: "Movies",
          newName: "NormalizedSearch");

      migrationBuilder.RenameColumn(
          name: "NormalizedName",
          table: "Directors",
          newName: "NormalizedSearch");

      migrationBuilder.RenameColumn(
          name: "NormalizedName",
          table: "Actors",
          newName: "NormalizedSearch");

      migrationBuilder.CreateIndex(
          name: "IX_Writers_NormalizedSearch",
          table: "Writers",
          column: "NormalizedSearch")
          .Annotation("Npgsql:TsVectorConfig", "english");

      migrationBuilder.CreateIndex(
          name: "IX_Movies_NormalizedSearch",
          table: "Movies",
          column: "NormalizedSearch")
          .Annotation("Npgsql:TsVectorConfig", "english");

      migrationBuilder.CreateIndex(
          name: "IX_Directors_NormalizedSearch",
          table: "Directors",
          column: "NormalizedSearch")
          .Annotation("Npgsql:TsVectorConfig", "english");

      migrationBuilder.CreateIndex(
          name: "IX_Actors_NormalizedSearch",
          table: "Actors",
          column: "NormalizedSearch")
          .Annotation("Npgsql:TsVectorConfig", "english");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
      migrationBuilder.DropIndex(
          name: "IX_Writers_NormalizedSearch",
          table: "Writers");

      migrationBuilder.DropIndex(
          name: "IX_Movies_NormalizedSearch",
          table: "Movies");

      migrationBuilder.DropIndex(
          name: "IX_Directors_NormalizedSearch",
          table: "Directors");

      migrationBuilder.DropIndex(
          name: "IX_Actors_NormalizedSearch",
          table: "Actors");

      migrationBuilder.RenameColumn(
          name: "NormalizedSearch",
          table: "Writers",
          newName: "NormalizedName");

      migrationBuilder.RenameColumn(
          name: "NormalizedSearch",
          table: "Movies",
          newName: "NormalizedTitle");

      migrationBuilder.RenameColumn(
          name: "NormalizedSearch",
          table: "Directors",
          newName: "NormalizedName");

      migrationBuilder.RenameColumn(
          name: "NormalizedSearch",
          table: "Actors",
          newName: "NormalizedName");
    }
  }
}
